// Diagram slots - Instruction Sheet B section 6 (slot IDs fixed; do not rename).
// Until the designer's SVGs arrive, each slot renders a plain bulleted list of the
// diagram's nodes as given in Sheet B (Sheet A 16.3).
// position: 'end' (after the section's own blocks), 'start' (top of section),
// 'after-table' (after the first table block in the section).

export const DIAGRAM_SLOTS = [
  // ---- Trust Accounting
  { id: 'dg-trust-accounting-01', section: 'trust-accounting--s2-1', position: 'end', title: 'Where the obligations live', type: 'Layered block diagram', nodes: ['Uniform Law (NSW) as applied by Application Act s 4', 'LPUL Ch 4 Pt 4.2 (ss 127-168)', 'LPUGR Ch 4 Pt 4.2 (rr 33-69) and Pt 4.6 (rr 91E-95A)', 'Application Act ss 11, 14, 46-47', 'Application Regulation Pt 3', 'ASCR rr 12.3, 37', 'Solicitors Rules r 6'] },
  { id: 'dg-trust-accounting-02', section: 'trust-accounting--s3-2', position: 'end', title: 'Section 34 and section 35', type: 'Two-panel diagram', nodes: ['s 34 Responsibilities of principals (two limbs)', 's 35 Liability of principals (two limbs; limb (b) highlighted as "the operative one")', 'Arrow from any practice breach to each principal'] },
  { id: 'dg-trust-accounting-03', section: 'trust-accounting--s4-7', position: 'end', title: 'Decision sequence for each receipt', type: 'Interactive flowchart', nodes: ['1. Entrusted in connection with legal services? If no, not trust money', '2. Services already provided and billed? Not trust money (s 129(2)(a))', '3. Financial service requiring an AFSL? Not trust money; give a s 134 notice', '4. Is it cash? (gold gate) It must go to the GTA (or CMA for controlled money) before anything else (s 143)', '5. Instructions to pay or deliver to a third party who is not an associate? Transit money (s 140)', '6. Written direction to deposit into a non-GTA account under the practice\'s exclusive control? Controlled money (s 139)', '7. Written direction from a person legally entitled to give it? Written direction money (s 137(a); r 34)', '8. Subject to a power to receive or disburse for another? Power money (s 141)', '9. Otherwise general trust money (ss 137, 138(1))', 'Each terminal node links to its records row in §22.1'] },
  { id: 'dg-trust-accounting-04', section: 'trust-accounting--s5', position: 'after-table', title: 'The five categories at a glance', type: 'Five columns plus Investment; tabs on screen, full grid in print', nodes: ['General trust money: trigger, what you must do, records, statement required', 'Controlled money: trigger, what you must do, records, statement required', 'Transit money: trigger, what you must do, records, statement required', 'Written direction money: trigger, what you must do, records, statement required', 'Power money: trigger, what you must do, records, statement required', 'Investment of trust money: trigger, what you must do, records, statement required'] },
  { id: 'dg-trust-accounting-05', section: 'trust-accounting--s6-3', position: 'end', title: 'The four absolute prohibitions', type: 'Four bold panels (static)', nodes: ['No intermixing (s 146)', 'No deficiency (s 148, with the penalty text)', 'No false names (s 147(3))', 'No borrowing from clients (ASCR r 12.3)'] },
  { id: 'dg-trust-accounting-06', section: 'trust-accounting--s7-1', position: 'end', title: 'The record architecture', type: 'Four horizontal layers', nodes: ['Source records: receipts, cheque butts, EFT authorisations, deposit slips, ADI statements', 'Books of prime entry: receipts cash book, payments cash book, transfer journal', 'Book of summary: trust ledger accounts', 'Reports: reconciliation, trial balance'] },
  { id: 'dg-trust-accounting-07', section: 'trust-accounting--s7-2', position: 'end', title: 'Money in: from receipt to ledger', type: 'Swimlane flow with timing badges', nodes: ['Receipt (r 36)', 'Deposit record (r 37)', 'Receipts cash book (r 44) within 5 working days', 'Trust ledger credit (r 47) within 5 working days', 'Control account monthly', 'Month end (r 48)'] },
  { id: 'dg-trust-accounting-08', section: 'trust-accounting--s7-4', position: 'end', title: 'Money out: cheque or EFT only', type: 'Flow with side panel', nodes: ['Authorised signatory (r 43(2))', 'Cheque (crossed "not negotiable", specified payee, practice name and "law practice trust account") or EFT (internal reference, confirmation printed)', 'Written payment record (r 43(3))', 'Payments cash book (r 45) within 5 working days', 'Trust ledger debit (r 47)', 'Side panel: the prohibited methods (cash, ATM, telephone)'] },
  { id: 'dg-trust-accounting-09', section: 'trust-accounting--s7-6', position: 'end', title: 'Double entry postings', type: 'Posting diagram', nodes: ['Receipt: Debit Control account (monthly total); Credit Trust ledger account (daily)', 'Receipt reversal: Debit Trust ledger account; Credit Control account', 'Payment: Debit Trust ledger account (daily); Credit Control account (monthly total)', 'Payment reversal: Debit Control account; Credit Trust ledger account', 'Transfer journal: lateral arrow between two ledgers, "no effect on the control account"'] },
  { id: 'dg-trust-accounting-10', section: 'trust-accounting--s8', position: 'start', title: 'Month end in one page', type: 'Two-branch diagram with deadline badge', nodes: ['Trial balance (r 48(2)(b)) tests internal records against each other - failure means something has been recorded against the wrong client', 'ADI reconciliation (r 48(2)(a)) tests internal records against the bank - failure means money may be missing. A deficiency', 'Deadline badge: 15 working days', 'Reconciliation format lines from §8.3 as a mini form'] },
  { id: 'dg-trust-accounting-11', section: 'trust-accounting--s9-2', position: 'end', title: 'Rule 42: the four methods', type: 'Decision flow mirroring the Method Selector', nodes: ['Is the money in a general trust account or controlled money account?', 'Is the client a commercial or government client with a compliant costs agreement authorising withdrawal? → Method 4', 'Is this reimbursement of a disbursement the practice has already paid? → Method 3', 'Do you hold instructions authorising this specific withdrawal? → Method 2', 'Otherwise → Method 1', 'Each method panel carries the "Requirement" and "Wait" text from the §9.2 table'] },
  { id: 'dg-trust-accounting-12', section: 'trust-accounting--s10-1', position: 'end', title: 'Controlled money flow', type: 'Flow with side note', nodes: ['Written direction (s 139(1), 7 years)', 'Establish CMA with an ADI, name per r 61', 'Controlled money receipt (r 62)', 'Movement record and register (r 64)', 'Monthly listing within 15 working days, principal-reviewed (r 64(9))', 'Withdrawals only per direction / r 42 / court order, cheque or EFT only, no BPAY (r 63)', 'Statement (r 52)', 'Side note: "interest belongs to the client"'] },
  { id: 'dg-trust-accounting-13', section: 'trust-accounting--s13-2', position: 'end', title: 'Statutory deposit: the calculation', type: 'Stepwise diagram', nodes: ['Lowest ADI balance in previous applicable period + statutory deposit that day = Base', '15-banking-day look-forward; if lower, 80%', 'Below $10,000 = nil', 'Round up to next $100', 'Deposit within 20 banking days', 'Quarter-end dates: 31 March, 30 June, 30 September, 31 December'] },
  { id: 'dg-trust-accounting-14', section: 'trust-accounting--s14-3', position: 'end', title: 'Irregularity: what to do', type: 'Five-step vertical flow (danger styling)', nodes: ['Stop', 'Make it good', 'Report', 'Take advice', 'Recover', 'Side panel: "Report it even if you have already fixed it"'] },
  { id: 'dg-trust-accounting-15', section: 'trust-accounting--s15-1', position: 'end', title: 'The annual cycle', type: 'Circular timeline', nodes: ['1 April trust year begins', '31 March year ends', '30 April Part A (every practice)', '31 May Part B and External Examiner\'s Report', '30 June trust account statements (given mid to late July)', 'July signatory notification', 'Quarterly statutory deposit reviews'] },
  { id: 'dg-trust-accounting-16', section: 'trust-accounting--s20', position: 'end', title: 'What examiners actually find', type: 'Horizontal bar chart (static)', nodes: ['317 - r 48(3) - Reconciliation statements not prepared within 15 days after month end', '218 - r 48(3) - Trust trial balances not prepared within 15 days of month end', '175 - Application Reg - Statutory deposit review not completed within the required banking days', '129 - r 44(3)', '107 - r 45(2)(b)', '89 - r 48', '74 - r 64(8)', '70 - Application Reg', '69 - r 52', '62 - r 47(3)(e)(i)', '55 - r 61(b)', '52 - r 47(4)(b)', '48 - r 52(4)(a)', '47 - r 48(1)', '45 - r 48(2)(a)(i)', '44 - r 43(1)(a)', 'The pattern: almost every breach is a timing breach on month end procedures or posting'] },
  // ---- Practice Management
  { id: 'dg-practice-management-01', section: 'practice-management--s1-2', position: 'end', title: 'What a winning firm looks like', type: 'Four-quadrant panel (static)', nodes: ['Appropriate structure for each practice group', 'Get the people puzzle right', 'Pricing', 'Have a point of difference'] },
  { id: 'dg-practice-management-02', section: 'practice-management--s1-3', position: 'end', title: 'The profit driver equation', type: 'Equation rendered large, factor tiles', nodes: ['Net profit per principal = (1 + L) × BR × CH × R × M', 'L - Leverage: Employed fee earners per equity principal', 'BR - Billing rate: Weighted average charge rate across all fee earners', 'CH - Chargeable hours: Weighted average annual chargeable hours per fee earner', 'R - Realisation: Conversion of WIP into billings', 'M - Profit margin: What is left after salaries and overheads'] },
  { id: 'dg-practice-management-03', section: 'practice-management--s1-5', position: 'end', title: 'Where to intervene', type: 'Two-part: driver tiles and performance bands', nodes: ['Leverage - Market - Biggest impact, hardest to move', 'Price - Market - Biggest impact, most used lever', 'Chargeable hours - Internal - Housekeeping. Fix it tomorrow', 'Realisation - Internal - Housekeeping. Fix it tomorrow', 'Margin - Internal - Housekeeping, but a secondary driver', '~$350,000: Average on all five drivers', '$350,000 to $700,000: Very good on two, one of which must be leverage or price, plus average on the other three', '$700,000+: Very good on two, average on the rest, plus a homogeneous culture'] },
  { id: 'dg-practice-management-04', section: 'practice-management--s1-6', position: 'end', title: 'Leverage: the denominator problem', type: 'Two simple figures with arithmetic (static)', nodes: ['Five fee earners over two principals = 2.5', 'Promote one: four over three = 1.33'] },
  { id: 'dg-practice-management-05', section: 'practice-management--s1-7', position: 'end', title: 'Battery hen versus free range', type: 'Two-column contrast card', nodes: ['Battery hen: Here is your salary. In return produce $X in fees. Here is your hourly rate, so here are your required hours. We will also measure your write-downs, your debtors and your WIP. We have expensive software, so we will look at it weekly and yell at you monthly', 'Free range: Delighted to have you. I will give you as much work as you can chew through. Do it to the best of your ability and capture the activity. Record your hours. If it is fixed fee work, recording hours matters more, because we need to know the cost of delivery', 'Free range people for as long as you can, then battery hen them.'] },
  { id: 'dg-practice-management-06', section: 'practice-management--s1-10', position: 'end', title: 'The money go round', type: 'Cash flow diagram', nodes: ['Bank account (centre)', 'Inflows: Owners, Loans', 'Outflows: Equipment, Drawings (→ Tax), Salaries and overheads', 'Production chain: WIP → Fees rendered → Debtors → Bank', 'Lock-up markers on WIP and Debtors', 'Leak marker on chargeable time', 'Loss markers on Fees rendered, Bad debts and Disbursements'] },
  { id: 'dg-practice-management-07', section: 'practice-management--s1-11', position: 'end', title: 'Why firms do not change', type: 'Four panels (static)', nodes: ['No urgency - The problem is absorbable. The solutions are uncomfortable', 'Inertia - The larger the firm the greater the inertia. It is all a bit too hard', 'Lack of ownership - I am fine, others are the problem. Find someone performing worse and point', 'Easier to wait it out - It has turned around before. Keep my head down'] },
  { id: 'dg-practice-management-08', section: 'practice-management--s1-12', position: 'end', title: 'The nine non-financial predictors', type: 'Scorecard with 1 to 5 scale', nodes: ['1. Client satisfaction is a top priority of the firm.', '2. The firm has no room for those who put their personal agenda ahead of the interests of clients or the firm.', '3. Those who contribute most to the overall success of the firm are the most highly rewarded.', '4. Management gets the best out of everybody in the firm.', '5. Around here you are required, not just encouraged, to learn new skills.', '6. The firm invests a significant amount of time in things that will pay off in the future.', '7. People within the office always treat others with respect.', '8. The quality of supervision of client files and projects is uniformly high.', '9. The quality of professionals in our office is as high as can be expected.'] },
  { id: 'dg-practice-management-09', section: 'practice-management--s3-2', position: 'end', title: 'Why most clients must pay more under fixed fees', type: 'Normal-distribution curve with three markers', nodes: ['Cheapest: Charge everyone the cheapest price: profit collapses', 'Average: Charge everyone the average: half pay more, half pay less, profit is unchanged', 'Highest: Charge everyone the highest price: profit rises significantly, but 29 of 30 clients pay more', 'Annotation: 68% within one standard deviation, 95% within two'] },
  { id: 'dg-practice-management-10', section: 'practice-management--s3-1', position: 'end', title: 'Three routes to $30,000', type: 'Three-column comparison', nodes: ['Work harder: Bill another 85 hours. At 60% chargeable, that is 142 extra hours, about 18 days', 'Add resources: At a 30% margin, render another $100,000. At $350/hour and 60% chargeable, about 476 person hours, or 60 days', 'Raise price 8.5%: Charge $380 instead of $350. Expenses unchanged. Same $30,000'] },
  { id: 'dg-practice-management-11', section: 'practice-management--s7-3', position: 'end', title: 'The four-step business plan', type: 'A → B → C → D loop with the KRO cube', nodes: ['Where are you today?', 'Where do you want to be in 12 months?', 'What strategies get you from A to B?', 'What actions sit under each strategy?', 'KRO cube: Service mix / Client mix / Practice mix'] },
  { id: 'dg-practice-management-12', section: 'practice-management--s7-5', position: 'end', title: 'Portfolio matrix', type: '2×2 with axes Attractiveness and Growth', nodes: ['Stars - high growth, high attractiveness. Challenging work people want to do. Invest', 'Question marks - possibly growing, but you are not passionate about the work or the clients. Interrogate whether you want this in the business', 'Cash cows - bread and butter. Not high growth, but they pay on time, they are easy, they do not drain you. These keep you going', 'Dogs - low growth, low attractiveness. No reason to keep doing this work', 'Three questions: is there demand, do I have a strength in it, and am I passionate about it?'] },
  { id: 'dg-practice-management-13', section: 'practice-management--s7-5', position: 'end', title: 'Three horizons', type: 'Three ascending curves', nodes: ['Horizon 1 - operators extend the core - 0 to 12 months - Set up the technology; find clients; build the website; update collateral to reflect a new position', 'Horizon 2 - business builders develop new opportunities - 1 to 5 years - Build a referral network or business association relationship; enter an adjacent service area', 'Horizon 3 - visionaries create viable options - Long term - Succession; partner health and capacity; what the business becomes when you stop'] },
  { id: 'dg-practice-management-14', section: 'practice-management--s7-6', position: 'end', title: 'Twelve ways to build top line growth', type: 'Three columns with item 12 set apart', nodes: ['Existing clients: 1. Increase fee rates; 2. Improve realisation; 3. Deepen; 4. Diversify', 'New clients: 5. New clients won through the sales efforts of existing team members; 6. New clients won by new sales channels; 7. Increase the quality, size and frequency of referrals from existing sources; 8. Expand the pool of referral sources; 9. Acquire clients (lateral hires, practice acquisition)', 'New products: 10. Commercialise existing products or services, including charging for things you currently give away; 11. Develop new products or services', '12. Reduce, stop or divest', 'Growth gets harder and more expensive as you move left to right'] },
  { id: 'dg-practice-management-15', section: 'practice-management--s8-2', position: 'end', title: 'The paramount duty', type: 'Centre node with four surrounding nodes', nodes: ['Duty to the court and the administration of justice (ASCR r 3.1)', 'Courts', 'Clients', 'Colleagues', 'Communities', 'Would my actions in some way damage the system I represent?'] },
  { id: 'dg-practice-management-16', section: 'practice-management--s8-5', position: 'end', title: 'Instructions: the three-box test', type: 'Three gates in sequence', nodes: ['Lawful - The easy one. You cannot assist someone to break the law', 'Proper - Am I being asked to do something contrary to my broader ethical duties or the conduct rules?', 'Competent - Am I satisfied the person understands the instructions and their consequences? In a commercial context, is this person authorised to give them?', 'If all three boxes are ticked, the rule says you must follow.'] },
  { id: 'dg-practice-management-17', section: 'practice-management--s9-6', position: 'end', title: 'The four pillars of practice growth', type: 'Four vertical pillars', nodes: ['1. Strategy - WHERE will I play? HOW will I compete? WHY will I win? - Outcome: FOCUS', '2. Marketing - AWARENESS (web, social, media); UNDERSTANDING (articles, industry engagement); CONSIDERATION and BELIEF (one to one, evidence) - Outcome: AWARE', '3. Business development - Triggers and filters; discussion; scope / price / pitch; go / no go - Outcome: INSTRUCT', '4. Client experience management - Enter; engage; exit - Outcome: Extend and defend', 'Marketing is one to many. Business development is one to one.'] },
  { id: 'dg-practice-management-18', section: 'practice-management--s9-12', position: 'end', title: 'Client pathways', type: 'Five-stage path', nodes: ['Entice - how you invest in your expertise, networks and reputation before the client arrives', 'Enter - what you do in first client meetings and at the start of a matter', 'Engage - the experience you create as you deliver, day to day', 'Exit - how you end specific projects, and reflect on the promise made and the value created', 'Extend - what happens beyond projects and matters to build your expertise, networks and reputation', 'Focusing question: how do I get, and give, the most from every touchpoint of my known networks?'] },
  { id: 'dg-practice-management-19', section: 'practice-management--s9-15', position: 'end', title: 'Importance versus urgency', type: '2×2', nodes: ['Important / Urgent: 1. Do it now', 'Important / Not urgent: 2. Decide when to do it', 'Not important / Urgent: 4. Delegate it', 'Not important / Not urgent: 3. Dump it', 'BD lives in box 2. Decide when.'] },
  // ---- Risk Management
  { id: 'dg-risk-management-01', section: 'risk-management--s1', position: 'end', title: 'The four numbers', type: 'Four large figure tiles (static)', nodes: ['37% of all claims arise from property and conveyancing', '42% of all claims are caused by poor communication with clients', '23% are caused by not knowing the law adequately', '>90% of cyber claims are caused by business email compromise'] },
  { id: 'dg-risk-management-02', section: 'risk-management--s2-2', position: 'end', title: 'The cover', type: 'Stacked bars', nodes: ['Primary policy: $2 million', 'Optional top up: up to $20 million total', 'Run-off cover: free and unlimited on the primary policy', 'Group cyber risk policy: free, up to $50,000 limit', 'Note: top-up run-off must be arranged separately'] },
  { id: 'dg-risk-management-03', section: 'risk-management--s2-6', position: 'end', title: 'Zakka v Elias', type: 'Simple decision diagram', nodes: ['Work done in the course of the practice → covered', 'Work done unsupervised, outside the practice, for a non-client, free of charge → "a frolic of her own" → not covered; personal exposure', 'Whether the firm takes on that client is at the principal\'s discretion', 'What fees are charged is at the principal\'s discretion', 'Nothing is done outside the firm\'s file and system'] },
  { id: 'dg-risk-management-04', section: 'risk-management--s3-1', position: 'end', title: 'Claims by area of law', type: 'Horizontal bar or donut (static)', nodes: ['Conveyancing 37%', 'Litigation 25%', 'General commercial 10%', 'Family law 10%', 'Wills and estates 10%', 'Mortgages and commercial borrowing 5%', 'Leases 2%', 'Sale and purchase of business 1%'] },
  { id: 'dg-risk-management-05', section: 'risk-management--s4-1', position: 'end', title: 'Causes of claims', type: 'Donut with click-to-drill', nodes: ['Poor communication with clients 42%', 'Not knowing the law adequately 23%', 'Document problems 16%', 'Systems problems 16%', 'Other (including no negligence) 3%', 'Drill-down: sub-cause tables in §4.2 to §4.5'] },
  { id: 'dg-risk-management-06', section: 'risk-management--s5-1', position: 'end', title: 'File note rules', type: 'Four rule cards (static)', nodes: ['There is no time limit on making a file note', 'Date it today', 'Never backdate a file note', 'A note made today about a July 2026 conversation is far better than nothing when the claim arrives in 2032'] },
  { id: 'dg-risk-management-07', section: 'risk-management--s6', position: 'end', title: 'Clients who bite', type: 'Seven tiles with click-to-reveal', nodes: ['The disappearing client - Fails to respond', 'The "don\'t involve me" client - Wants the solicitor to make the decisions', 'The transferred client - Won\'t pay the former solicitor\'s fees; the file is usually poor', 'The extended family client - Who is actually the client?', 'The experienced claimant client - Notorious fee dodger', 'The non-English speaking client - Who is interpreting?', 'The family and friend client - Potential for conflict and lack of detailed file notes'] },
  { id: 'dg-risk-management-08', section: 'risk-management--s6-3', position: 'end', title: 'Transferred file due diligence', type: 'Vertical checklist flow', nodes: ['Conflict check', 'Review the file to confirm you have sufficient resources and people available', 'Confirm you have the whole file - there may be a lien over it with the previous firm', 'Assess the quality of the file', 'Explain that you must review the work done in its entirety', 'Ask about objectives and expectations afresh', 'Ask whether they saw anyone before that firm', 'If the answer is yes, you are the third firm'] },
  { id: 'dg-risk-management-09', section: 'risk-management--s8-6', position: 'end', title: 'Supervision structure', type: 'Six-part structure', nodes: ['Identify the right person', 'Explain and assign roles', 'Develop rapport and a relationship', 'Make time', 'Carry out regular file reviews', 'Use checklists'] },
  { id: 'dg-risk-management-10', section: 'risk-management--s9-2', position: 'end', title: 'Vision, mission, values, goals', type: 'Four-row structured panel with a "Your practice" column', nodes: ['Vision', 'Mission', 'Values', 'Goals', 'Your practice (blank column for the user\'s note)'] },
  { id: 'dg-risk-management-11', section: 'risk-management--s9-4', position: 'end', title: 'Horizon gazing', type: 'Fillable grid; rows 3 to 5 highlighted', nodes: ['1. Legal practice overall', '2. Practice areas', '3. Technology / AI (current live one)', '4. Cyber crime risk management (current live one)', '5. Regulatory reforms (current live one)', '6. Recruitment', '7. Education / training needs', '8. Other', 'Columns: Emerging development / Challenges / Budget impacts / Opportunities'] },
  { id: 'dg-risk-management-12', section: 'risk-management--s10-3', position: 'end', title: 'The double excess', type: 'Single strong panel (danger border)', nodes: ['Excess: EXCEPT THAT excess means twice that amount for claims arising from any payment or electronic funds transfer made on an instruction or authorisation that the law practice did not take reasonable steps to verify.', 'Independently verify account details before making any payment', 'Set a value threshold above which you telephone the payee on a number you already hold', 'Require secondary verification of any change to payment instructions', 'Use dual authorisation for EFTs'] },
  { id: 'dg-risk-management-13', section: 'risk-management--s10-4', position: 'end', title: 'Cyber security response plan', type: 'Vertical flow', nodes: ['Risk based assessment', 'Asset audit', 'Vulnerability assessment', 'Expert advice', 'Risk framework and governance', 'Accountability', 'Cyber security policies', 'Monitoring and review', 'Cyber incident management', 'Record keeping'] },
  { id: 'dg-risk-management-14', section: 'risk-management--s10-1', position: 'end', title: 'Cyber-assisted fraud claims', type: 'Dual-axis bar chart (static)', nodes: ['2017/18: 10 claims, $1.1m', '2018/19: 21 claims, $1.2m', '2019/20: 26 claims, $2.5m', '2020/21: 44 claims, $3.1m', '2021/22: 37 claims, $1.5m', '2022/23: 38 claims, $3.4m', '2023/24: 41 claims, $2.7m', '2024/25: 33 claims, $1.8m', '2025/26: 27 claims, $2.0m', 'Total $19.32m to 31 May 2026'] },
];

export function diagramSlotHtml(slot) {
  // The designer's SVG (inlined at build time, HANDOVER §2.3) replaces the placeholder list.
  const asset = typeof App !== 'undefined' && App.data && App.data.diagrams ? App.data.diagrams[slot.id] : null;
  const body = asset
    ? asset
    : `<div class="diagram-placeholder"><p class="diagram-placeholder-note">Diagram placeholder (${escapeHtml(slot.type)}). Nodes:</p><ul>` + slot.nodes.map((n) => `<li>${escapeHtml(n)}</li>`).join('') + `</ul></div>`;
  return `<figure class="diagram-slot${asset ? ' has-asset' : ''}" id="${escapeAttr(slot.id)}" data-title="${escapeAttr(slot.title)}" data-diagram-type="${escapeAttr(slot.type)}">${body}<figcaption>${escapeHtml(slot.title)}</figcaption></figure>`;
}
